/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.decol.campo.ventanas;

import com.decol.campo.controladores.GestorCampo;
import com.decol.campo.modelos.TablaLotesModel;
import com.decol.campo.modelos.TipoSuelo;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielmainero
 */
public class PantallaAdministracionCampo extends javax.swing.JFrame {

    private final List<TipoSuelo> tiposSuelos;
    private final GestorCampo gestor;
    private final TablaLotesModel tablaLotesModel;
    
    public PantallaAdministracionCampo(List<TipoSuelo> tiposSuelos, GestorCampo gestor) {
        this.tiposSuelos = tiposSuelos;
        this.gestor =  gestor;
        this.tablaLotesModel = new TablaLotesModel(gestor.getLotesTemporales());
        initComponents();
        //Inicializamos los errores
        lblExisteNombreCampo.setVisible(false);
        lblExisteNumeroLote.setVisible(false);
        //Hacemos foco en el nombre del campo
        txtNombreCampo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreCampo = new javax.swing.JLabel();
        txtNombreCampo = new javax.swing.JTextField();
        lblSuperficieCampo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblSuperficieLote = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumeroLote = new javax.swing.JLabel();
        lblTipoSuelo = new javax.swing.JLabel();
        cmbTipoSuelo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        lblExisteNumeroLote = new javax.swing.JLabel();
        btnAgregarLote = new javax.swing.JButton();
        btnEditarLote = new javax.swing.JButton();
        btnQuitarLote = new javax.swing.JButton();
        txtNumeroLote = new javax.swing.JTextField();
        txtSuperficieLote = new javax.swing.JTextField();
        lblExisteNombreCampo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuarioRegistra = new javax.swing.JLabel();
        btnRegistrarCampo = new javax.swing.JButton();
        btnCancelarRegistrarCampo = new javax.swing.JButton();
        txtSuperficieCampo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Campo");

        lblNombreCampo.setText("Nombre:");

        txtNombreCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreCampoFocusLost(evt);
            }
        });

        lblSuperficieCampo.setText("Superficie:");

        jLabel3.setText("ha.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lotes"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("Tenga en cuenta que debe ingresar al menos 1 Lote");

        lblSuperficieLote.setText("Superficie:");

        jLabel6.setText("ha.");

        lblNumeroLote.setText("Nro.:");

        lblTipoSuelo.setText("Tipo de suelo:");

        cmbTipoSuelo.setModel(new javax.swing.DefaultComboBoxModel(tiposSuelos.toArray()));

        tblLotes.setModel(tablaLotesModel);
        jScrollPane1.setViewportView(tblLotes);

        lblExisteNumeroLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblExisteNumeroLote.setForeground(new java.awt.Color(255, 51, 51));
        lblExisteNumeroLote.setText("Este nro. de Lote ya está en uso");

        btnAgregarLote.setText("Agregar Lote");
        btnAgregarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLoteActionPerformed(evt);
            }
        });

        btnEditarLote.setText("Editar");

        btnQuitarLote.setText("Quitar");

        txtNumeroLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroLoteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExisteNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSuperficieLote)
                                    .addComponent(lblNumeroLote)
                                    .addComponent(lblTipoSuelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgregarLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitarLote)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroLote)
                            .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSuperficieLote)
                            .addComponent(jLabel6)
                            .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoSuelo)
                            .addComponent(cmbTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExisteNumeroLote))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLote)
                    .addComponent(btnEditarLote)
                    .addComponent(btnQuitarLote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblExisteNombreCampo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblExisteNombreCampo.setForeground(new java.awt.Color(255, 51, 51));
        lblExisteNombreCampo.setText("Este nombre ya está en uso");

        lblUsuario.setText("Usuario:");

        btnRegistrarCampo.setText("Registrar Campo");
        btnRegistrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCampoActionPerformed(evt);
            }
        });

        btnCancelarRegistrarCampo.setText("Cancelar");
        btnCancelarRegistrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistrarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarRegistrarCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarCampo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSuperficieCampo)
                                .addComponent(lblNombreCampo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblExisteNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblUsuarioRegistra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCampo)
                    .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExisteNombreCampo)
                    .addComponent(lblUsuario)
                    .addComponent(lblUsuarioRegistra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuperficieCampo)
                    .addComponent(jLabel3)
                    .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCampo)
                    .addComponent(btnCancelarRegistrarCampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCampoFocusLost
        // verificamos si ya existe un campo con ese nombre
        if (gestor.tomarNombreCampo(txtNombreCampo.getText())) {
            //Mostramos error y hacemos foco en el nombre
            lblExisteNombreCampo.setVisible(true);
            txtNombreCampo.requestFocus();
        }
        else{
            lblExisteNombreCampo.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreCampoFocusLost

    private void btnAgregarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLoteActionPerformed
        // validamos los datos minimos
        if (txtNumeroLote.getText().isEmpty() || txtSuperficieLote.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos del Lote son obligatorios");
        }
        else{
            Integer numeroLote = Integer.parseInt(txtNumeroLote.getText());
            BigDecimal superficieLote = new BigDecimal(txtSuperficieLote.getText().replaceAll(",", "."));
            TipoSuelo tipoSuelo = (TipoSuelo) cmbTipoSuelo.getSelectedItem();
            gestor.agregarLoteTemporal(numeroLote, superficieLote, tipoSuelo);
        }
    }//GEN-LAST:event_btnAgregarLoteActionPerformed

    private void btnRegistrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCampoActionPerformed
        tomarFinIngresoLotes();
    }//GEN-LAST:event_btnRegistrarCampoActionPerformed

    private void btnCancelarRegistrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistrarCampoActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarRegistrarCampoActionPerformed

    private void txtNumeroLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroLoteFocusLost
        if(!txtNumeroLote.getText().isEmpty()){
            // verificamos si ya existe un lote en el campo con ese numero
            if (gestor.tomarNumeroLote(Integer.parseInt(txtNumeroLote.getText()))) {
                //Mostramos error y hacemos foco en el numero
                lblExisteNumeroLote.setVisible(true);
                txtNumeroLote.requestFocus();
            }
            else{
                lblExisteNumeroLote.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtNumeroLoteFocusLost

    private void tomarFinIngresoLotes(){
        String nombreCampo = txtNombreCampo.getText();
        BigDecimal superficieCampo = null;
        if(!txtSuperficieCampo.getText().isEmpty())
            superficieCampo = new BigDecimal(txtSuperficieCampo.getText().replaceAll(",", "."));
        gestor.tomarFinIngresoLotes(nombreCampo, superficieCampo);
    }
    
    public void mostrarLotesRegistrados(){
        //Limpiamos los campos
         txtNumeroLote.setText("");
         txtSuperficieLote.setText("");
         cmbTipoSuelo.setSelectedIndex(0);
         //hacemos foco al numero de lote
         txtNumeroLote.requestFocus();
         //recargamos la tabla
         tablaLotesModel.fireTableDataChanged();
    }
    
    public void pedirConfirmacionRegistrarCampo() {
        int registrarCampo = JOptionPane.showConfirmDialog (null, "¿Confirma el registro del Campo?", "Registrar Campo", JOptionPane.YES_NO_OPTION);
                if (registrarCampo == JOptionPane.YES_OPTION) {
            gestor.tomarConfirmacionRegistrarCampo();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLote;
    private javax.swing.JButton btnCancelarRegistrarCampo;
    private javax.swing.JButton btnEditarLote;
    private javax.swing.JButton btnQuitarLote;
    private javax.swing.JButton btnRegistrarCampo;
    private javax.swing.JComboBox<String> cmbTipoSuelo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExisteNombreCampo;
    private javax.swing.JLabel lblExisteNumeroLote;
    private javax.swing.JLabel lblNombreCampo;
    private javax.swing.JLabel lblNumeroLote;
    private javax.swing.JLabel lblSuperficieCampo;
    private javax.swing.JLabel lblSuperficieLote;
    private javax.swing.JLabel lblTipoSuelo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioRegistra;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtNombreCampo;
    private javax.swing.JTextField txtNumeroLote;
    private javax.swing.JTextField txtSuperficieCampo;
    private javax.swing.JTextField txtSuperficieLote;
    // End of variables declaration//GEN-END:variables
}
